apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sept16-test-setup-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sept16-test-setup-1 
  name: sept16-test-setup-1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: sept16-test-setup-1 
